#!/usr/bin/env bash

# all 'test's before 'ue' or will exit when test fails
test "$WITH_RVM" || WITH_RVM="true"

set -xue

start_path="$( pwd )"

# I really dislike using rvm gemset, but while testing this 
# script I got sick having to install the same gems over and
# over again.
if [[ $WITH_RVM == "true" ]]; then
        rvm gemset create radiant_development
        rvm gemset use radiant_development
fi

cd ~/radiant

# ensure fresh cache_buster code
rm -rf vendor/extensions/cache_buster
cp -r $start_path vendor/extensions/cache_buster
bundle update radiant-cache_buster-extension

RAILS_ENV=test bundle exec rake spec:extensions EXT=cache_buster --trace
